version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=taskdb
      - DB_SSL_MODE=disable
      - JWT_SECRET=your-super-secret-jwt-key-here
      - PORT=8080
    depends_on:
      - postgres
    networks:
      - task-network

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network

volumes:
  postgres_data:

networks:
  task-network:
    driver: bridge